-- ARCO Emblg packaging snapshots.
-- Run this once in the Supabase SQL editor for project mpkpehuatqsubohltssi.

create table if not exists public.packaging_orders (
  id bigint generated by default as identity primary key,
  source_order_id bigint not null,
  source_order_key text not null,
  customer_name text not null,
  confirmed_at timestamptz,
  items jsonb not null default '[]'::jsonb,
  archived_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists packaging_orders_active_idx
  on public.packaging_orders (archived_at, confirmed_at, id);
create index if not exists packaging_orders_customer_idx
  on public.packaging_orders (lower(customer_name));
create index if not exists packaging_orders_source_idx
  on public.packaging_orders (source_order_id);

alter table public.packaging_orders enable row level security;

grant select, insert, update on public.packaging_orders to authenticated;
grant usage, select on sequence public.packaging_orders_id_seq to authenticated;

drop policy if exists "packaging staff can read snapshots" on public.packaging_orders;
create policy "packaging staff can read snapshots"
  on public.packaging_orders for select to authenticated
  using (exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('operator', 'admin')));

drop policy if exists "packaging staff can create snapshots" on public.packaging_orders;
create policy "packaging staff can create snapshots"
  on public.packaging_orders for insert to authenticated
  with check (exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('operator', 'admin')));

drop policy if exists "packaging staff can archive snapshots" on public.packaging_orders;
create policy "packaging staff can archive snapshots"
  on public.packaging_orders for update to authenticated
  using (exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('operator', 'admin')))
  with check (exists (select 1 from public.user_roles ur where ur.user_id = (select auth.uid()) and ur.role in ('operator', 'admin')));
